### ISSUE TITLE
Code breaks at super() clause in __init__ function 

### ISSUE THREAD

**Issue by LuukOudshoorn25** [rlwastro/mastcasjobs#2]
When running a simple code using mastcasjobs.py, the code breaks with the following error. I have not yet been able to get a fix for this. 

~/anaconda3/lib/python3.7/site-packages/mastcasjobs.py in __init__(self, username, password, userid, request_type, context, base_url, wsid_url, fast_url)
     97 
     98         super(MastCasJobs,self).__init__(userid=userid, password=password,
---> 99                 base_url=base_url, request_type=request_type, context=context)
    100 
    101     def list_tables(self, context="MYDB"):

TypeError: __init__() got an unexpected keyword argument 'request_type'

**Comment by rlwastro** [comment]
I think you do not have the current version of the casjobs.py module.  Try installing it with the command in the readme file:

`pip install git+git://github.com/dfm/casjobs@master`

**Comment by LuukOudshoorn25** [comment]
Ah excellent. I had run that command before and that did not work. Not I forced an uninstall of casjobs first (pip uninstall casjobs) and next run your command. Now things work. Thanks a lot.
