### ISSUE TITLE
Quick jobs no longer working

### ISSUE THREAD

**Issue by MikeeRead** [rlwastro/mastcasjobs#3]
Hi

I'd been using mastcastjobs to successfully run quick queries for several days eg 

jobs = mastcasjobs.MastCasJobs(username=un, password=pwd, context="PanSTARRS_DR2")
checkResults = jobs.quick(checkQuery, task_name="check")
jobs.drop_table_if_exists(myDBTable)

since yesterday I've been getting errors. ExecuteQuickJob failed with status: 500

I'm also getting these errors going back to previous successful queries. I can run the same queries interactively via the quick web form.

I've contacted archive support but am wondering if anything has changed with the API's interface. Our mastcasjobs was installed 9 days ago and seems to point to the https URL

base_url="https://mastweb.stsci.edu/ps1casjobs/services/jobs.asmx",

the jobs submitted via mastcasjobs do not seem to reach my "history". Before they were (even the ones that failed I think).

Anyone else see the same issue?

Thanks
  Mike

**Comment by rlwastro** [comment]
Hi Mike, I just did a test with a simple query in the quick queue and it worked for me.  But I have seen the error you report from some quick jobs.  It looks like an error status gets returned for a 2-part query in the quick queue.  For example, this query returns a status 500 failure:
```
select top 1 * into #tmp from ObjectThin;
go
select * from #tmp;
```
Even though the return from mastcasjobs indicates an error, if I look in the History using the casjobs web form, it says that the query succeeded.  And if you run it interactively in the web form it also works.  A similar query without the `go` works from mastcasjobs:
```
select top 1 * into #tmp from ObjectThin;
select * from #tmp;
```
So two questions for you:
1. Do your queries have a multi-part structure like this?
2. If you look at your casjobs history in the web interface, do you see these queries?  Did they succeed or fail?

I so far have not identified what the problem is, although I suspect it goes all the way back to the casjobs service interface.  I am digging further into to it, so any additional info you can provide would be helpful.

**Comment by MikeeRead** [comment]
Hi Rick

Thanks.

No the queries are not multi-part.

Basically I'm downloading large tables bit by bit. I have a check query, the actual query that outputs to a myDb table and then the quick table download as astrpoy table. Then a quick query to drop the table

The log of the basic loop is below. This was all working fine, 300 million rows downloaded until it stalled yesterday on the myDB table delete.

I've heard back from Bernie (who was away) and it might be a web application firewall (WaF) issue, maybe I'm flagged as a DOS attacker! I was only running a single thread and Bernie suggested I go this route though.

If queries work for you looks like it probably is that side of things but I appreciate you having a look and providing this software that will hopefully get me the data, which is the bulkof DR2!

Cheers
  Mike

2020-07-01 16:51:10;INFO;CHECKQUERY=select count(*) as c from StackObjectAttributes where objID < 70612877995812447 or ( objID=70612877995812447 and uniquePspsSTid <= 3675030000018031 )
2020-07-01 16:51:12;INFO;CHECKRESULTS=16000000
2020-07-01 16:51:12;INFO;LOOP=1
2020-07-01 16:51:12;INFO;QUERY=select top 125000 * into mr_StackObjectAttributes_70612877995812447 from StackObjectAttributes where objID > 70612877995812447 or ( objID=70612877995812447
 and uniquePspsSTid > 3675030000018031 )  order by objID,uniquePspsSTid
2020-07-01 16:51:12;INFO;MYDBTABLE=mr_StackObjectAttributes_70612877995812447
2020-07-01 16:51:12;INFO;OBJID=70612877995812447
2020-07-01 16:51:12;INFO;OTHERID=3675030000018031
2020-07-01 16:51:28;INFO;RESULTS=Rows Affected -------------        125000
2020-07-01 16:52:44;INFO;STARTSORT=
2020-07-01 16:52:44;INFO;ENDSORT=
2020-07-01 16:52:44;INFO;ROWSRETURNED=125000
2020-07-01 16:52:44;INFO;MAXOBJID=70622252216607129
2020-07-01 16:52:44;INFO;LASTOBJID=70622252216607129
2020-07-01 16:52:44;INFO;LASTOTHERID=3721153000005954
2020-07-01 16:52:44;INFO;OBJIDSMATCH=TRUE
2020-07-01 16:52:44;INFO;STARTWRITE=
2020-07-01 16:53:09;INFO;ENDWRITE=

**Comment by MikeeRead** [comment]
When the script was working I was seeing the queries in the casjobs history. Now I don't see them, so it looks like that are not even getting that far (bounced by the WAF?)

**Comment by rlwastro** [comment]
I think the fact that the queries do not get to the casjobs history at all probably does indicate another problem, and Bernie's suggestion that it is a firewall issue is likely to be correct.
It looks like it is possible to at least generate a more informative error message when a query fails, which would be helpful in diagnosing this sort of problem.  I will work on making that change.

**Comment by rlwastro** [comment]
If you install the latest version of the casjobs module, you will get more informative error messages when queries fail.  This should do the trick:
```
pip install --upgrade git+git://github.com/dfm/casjobs@master
```
This is helpful if there is a SQL syntax error (e.g., an unknown column name or table, or an error in the query), and for other kinds of service errors it shows the start of the Java traceback. E.g., the error for a missing table name is:
```
Exception: ExecuteQuickJob failed with status: 500
Invalid object name 'NoSuchTable'. 
```
And the error for a query that times out is:
```
Exception: ExecuteQuickJob failed with status: 500
Query exceeds queue time.  Please revise your query or use a longer queue. 
```

**Comment by MikeeRead** [comment]
Thanks I'll update as it'll be useful in the future.

My, unchanged, script started working again last night. So I presume something happened at the far end to cause this though I have not heard anything. It did just hang early morning for several hours doing nothing as far as I can tell (which i don't understand , no errors) but I killed it and restarted and it has done  another 10 million rows this morning

I'll close this issue as it wasn't really a mastcasjobs issue anyhow!

Thanks again, Mike
