### ISSUE TITLE
getting 500 status errors again

### ISSUE THREAD

**Issue by MikeeRead** [rlwastro/mastcasjobs#4]
Hi Rick

My mastcasjobs quick queue script has been running happily for about a week.

Yesterday evening it started giving errors, as did my long queue casjobs scripts, 

More info since you added the error retrieval.

the mastjobs quick is giving

ExecuteQuickJob failed with status: 500
System.Data.SqlClient.SqlException: Could not find prepared statement with handle -1.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)

and similar for the long queue casjobs

SubmitJob failed with status: 500
System.Data.SqlClient.SqlException: Could not find prepared statement with handle -1.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)

As before I'm not seeing these queries reach my history via the web interface.

I've emailed archive support but wondering 

a) if mastcasjobs queries work for you
b) any ideas

Thanks!

Mike

**Comment by rlwastro** [comment]
Thanks for reporting the issue.  This is a generic problem with the STScI Casjobs web services (not specific to the mastcasjobs module).  We will identify the issue & fix it asap.

**Comment by MikeeRead** [comment]
many thanks, I'm happy for this issue to be closed or left open as a way of updating.

**Comment by rlwastro** [comment]
This is now fixed – thanks again for reporting the issue!  We did not know about it before your report.

**Comment by caseyjlaw** [comment]
I am seeing this error today when using a fresh install on python3.6 and osx.
I can reproduce the error with the example query in the README for mastcasjobs.

**Comment by rlwastro** [comment]
Hi @caseyjlaw -- Yep, I confirm that the queue was hosed.  This should be fixed now.

**Comment by caseyjlaw** [comment]
Thanks!
