### ISSUE TITLE
incompatibility with casjobs (python) master branch

### ISSUE THREAD

**Issue by caseyjlaw** [rlwastro/mastcasjobs#6]
I'm walking through your readme to test a simple query to CasJobs via the python CasJobs (by dfm).
When doing that, I get this error:
`TypeError: __init__() got an unexpected keyword argument 'request_type'`

It seems that the python CasJobs library defines a class but does not take "request_type" as an argument.

**Comment by rlwastro** [comment]
I think this probably indicates that you need to update your version of the casjobs module.  The version that you get from a simple pip install is way out of date.  If you already have a more recent version installed, you might need to use `upgrade` to get the latest version:

```pip install --upgrade git+git://github.com/dfm/casjobs@master```

**Comment by caseyjlaw** [comment]
Ah, yes. That fixed it. Thanks for the quick reply, Rick.
