### ISSUE TITLE
Error when using list_tables()

### ISSUE THREAD

**Issue by JannisNe** [rlwastro/mastcasjobs#7]
I have a script that uses the ```list_tables``` method.
When executing I get
```
File "[...]/python3.9/site-packages/mastcasjobs.py", line 118, in list_tables
    return [l[1:-1]for l in res.split('\n')[1:-1]]
AttributeError: 'Table' object has no attribute 'split'
```

```list_tables()``` assumes the output of ```quick```to be a string but it was changed to be a ```Table``` by default. That is what's causing the problem I presume.

**Comment by rlwastro** [comment]
Now fixed with the pull request.
